version: "3.8"

configs:
  rabbitmq_conf:
    file: ./config/rabbitmq/rabbitmq.conf
  rabbitmq_definitions:
    file: ./config/rabbitmq/definitions.json
  rabbitmq_init:
    file: ./scripts/rabbitmq-init.sh
  redis_conf:
    file: ./config/redis/redis.conf
    
volumes:
  rabbitmq1_data:
  rabbitmq2_data:
  rabbitmq3_data:
  redis_data:

networks:
  fog-network:
    driver: overlay
    attachable: true

# Common Templates

x-rabbitmq-common-env: &rabbitmq-common-env
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_PASS: ${REDIS_PASS}
  RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
  MQ_ADMIN_USER: ${MQ_ADMIN_USER}
  MQ_ADMIN_PASS: ${MQ_ADMIN_PASS}
  MQ_NODE1_WORKER: ${MQ_NODE1_WORKER}
  MQ_NODE1_PASS: ${MQ_NODE1_PASS}
  MQ_NODE2_WORKER: ${MQ_NODE2_WORKER}
  MQ_NODE2_PASS: ${MQ_NODE2_PASS}
  MQ_NODE3_WORKER: ${MQ_NODE3_WORKER}
  MQ_NODE3_PASS: ${MQ_NODE3_PASS}

x-rabbitmq-base: &rabbitmq-base
  image: rabbitmq:4.1.6-management-alpine
  configs:
    - source: rabbitmq_conf
      target: /etc/rabbitmq/rabbitmq.conf
      mode: 0444
    - source: rabbitmq_definitions
      target: /etc/rabbitmq/definitions.json
      mode: 0444
    - source: rabbitmq_init
      target: /init.sh
      mode: 0555
  networks:
    - fog-network
  entrypoint: ["/bin/bash", "-c"]
  healthcheck:
    test: ["CMD", "rabbitmq-diagnostics", "ping"]
    interval: 30s
    timeout: 15s
    retries: 5
    start_period: 120s
  deploy:
    replicas: 1
    restart_policy:
          condition: on-failure
          delay: 10s
          max_attempts: 3
          window: 120s
    resources:
      limits:
        cpus: "1.0"
        memory: 512M
      reservations:
        cpus: "0.5"
        memory: 256M

# Services

services:
  redis:
    hostname: redis
    image: redis:latest
    configs:
      - source: redis_conf
        target: /etc/redis/redis.conf
        mode: 0444
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - fog-network
    command: "redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --loglevel warning --requirepass ${REDIS_PASSWORD}"
    # command: "redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASS}"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    deploy:
      placement:
          constraints:
            - node.hostname == manager1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

  rabbitmq1:
    <<: *rabbitmq-base
    hostname: rabbitmq1
    ports:
      - "15672:15672"
    environment:
      <<: *rabbitmq-common-env
      RABBITMQ_NODENAME: rabbit@rabbitmq1
      CLUSTER_WITH: ""
    deploy:
      placement:
          constraints:
            - node.hostname== manager1
    volumes:
      - rabbitmq1_data:/var/lib/rabbitmq
    command: |
      "rabbitmq-server &
       sleep 10
       /bin/bash /init.sh 2>&1 | tee /var/log/init.log
       wait"

  rabbitmq2:
    <<: *rabbitmq-base
    hostname: rabbitmq2
    ports:
      - "15673:15672"
    environment:
      <<: *rabbitmq-common-env
      RABBITMQ_NODENAME: rabbit@rabbitmq2
      CLUSTER_WITH: "rabbit@rabbitmq1"
    deploy:
      placement:
          constraints:
            - node.hostname == manager2
    volumes:
      - rabbitmq2_data:/var/lib/rabbitmq
    command: |
      "rabbitmq-server &
       sleep 15
       /bin/bash /init.sh 2>&1 | tee /var/log/init.log
       wait"

  rabbitmq3:
    <<: *rabbitmq-base
    hostname: rabbitmq3
    ports:
      - "15674:15672"
    environment:
      <<: *rabbitmq-common-env
      RABBITMQ_NODENAME: rabbit@rabbitmq3
      CLUSTER_WITH: "rabbit@rabbitmq1"
    deploy:
      placement:
          constraints:
            - node.hostname == manager3
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq
    command: |
      "rabbitmq-server &
       sleep 20
       /bin/bash /init.sh 2>&1 | tee /var/log/init.log
       wait"

  # scheduler:
  #   build: ./scheduler
  #   depends_on:
  #     - rabbitmq1
  #     - rabbitmq2
  #     - rabbitmq3
  #     - redis
  #   environment:
  #     NODE_NAME: ${MQ_ADMIN_USER}
  #     RABBITMQ_URL: amqp://${MQ_ADMIN_USER}:${MQ_ADMIN_PASS}@rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672/fog
  #     REDIS_URL: redis:6379
  #     REDIS_PASSWORD: ${REDIS_PASS}
  #   networks:
  #     - fog-network
  #   deploy:
  #     placement:
  #       constraints: [node.role!=manager]
  #     resources:
  #       limits:
  #         cpus: "1.0"
  #         memory: 1G

  # fog-node-1:
  #   build: ./fog-node
  #   depends_on:
  #     - rabbitmq1
  #     - rabbitmq2
  #     - rabbitmq3
  #     - redis
  #   environment:
  #     NODE_NAME: ${MQ_NODE1_WORKER}
  #     RABBITMQ_URL: amqp://${MQ_NODE1_WORKER}:${MQ_NODE1_PASS}@rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672/fog
  #     REDIS_URL: redis:6379
  #     REDIS_PASSWORD: ${REDIS_PASS}
  #     NODE_CPU_LIMIT: "0.5"
  #   deploy:
  #     placement:
  #       constraints: [node.labels.fog==1, node.role!=manager]
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M
  #   networks:
  #     - fog-network

  # fog-node-2:
  #   build: ./fog-node
  #   depends_on:
  #     - rabbitmq1
  #     - rabbitmq2
  #     - rabbitmq3
  #     - redis
  #   environment:
  #     NODE_NAME: ${MQ_NODE2_WORKER}
  #     RABBITMQ_URL: amqp://${MQ_NODE2_WORKER}:${MQ_NODE2_PASS}@rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672/fog
  #     REDIS_URL: redis:6379
  #     REDIS_PASSWORD: ${REDIS_PASS}
  #     NODE_CPU_LIMIT: "1.0"
  #   deploy:
  #     placement:
  #       constraints: [node.labels.fog==2, node.role!=manager]
  #     resources:
  #       limits:
  #         cpus: '1.0'
  #         memory: 1024M
  #   networks:
  #     - fog-network

  # fog-node-3:
  #   build: ./fog-node
  #   depends_on:
  #     - rabbitmq1
  #     - rabbitmq2
  #     - rabbitmq3
  #     - redis
  #   environment:
  #     NODE_NAME: ${MQ_NODE3_WORKER}
  #     RABBITMQ_URL: amqp://${MQ_NODE3_WORKER}:${MQ_NODE3_PASS}@rabbitmq1:5672,rabbitmq2:5672,rabbitmq3:5672/fog
  #     REDIS_URL: redis:6379
  #     REDIS_PASSWORD: ${REDIS_PASS}
  #     NODE_CPU_LIMIT: "0.75"
  #   deploy:
  #     placement:
  #       constraints: [node.labels.fog==3, node.role!=manager]
  #     resources:
  #       limits:
  #         cpus: '0.75'
  #         memory: 768M
  #   networks:
  #     - fog-network

