app:
  name: Optimized rabbitmq scheduler
  env: development
  owner: crabzie

http:
  port: 8080
  hostname: localhost

logger:
  level: debug
  development: true
  disableStacktrace: false
  encoding: json
  encoderConfig:
    nameKey: Service
    timeKey: Timestamp
    levelKey: Level
    callerKey: Caller
    messageKey: Msg
    stacktraceKey: Stacktrace
    consoleSeparator: " | "

db:
  connection: postgresql
  database: schedulerdb
  host: 127.0.0.1
  port: 5432
  name: postgres
  user: postgres
  password: SecurePostgresql2025!

redis:
  host: localhost
  port: 6379
  addr: localhost:6379
  password: SecureRedis2025!
