global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq-node1'
    static_configs:
      - targets: ['rabbitmq1:15692']
        labels:
          node: rabbitmq1


  - job_name: 'fog-node-1'
    static_configs:
      - targets: ['fog-node-1:2112']
        labels:
          instance: worker1

  - job_name: 'fog-node-2'
    static_configs:
      - targets: ['fog-node-2:2112']
        labels:
          instance: worker2
