global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          node: rabbitmq


  - job_name: 'fog-nodes'
    static_configs:
      - targets: ['fog-node-1:2112']
        labels:
          instance: fog-node-1
      - targets: ['fog-node-2:2112']
        labels:
          instance: fog-node-2
      - targets: ['fog-node-3:2112']
        labels:
          instance: fog-node-3
