global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: fog-scheduler
    environment: production

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq-node1'
    static_configs:
      - targets: ['rabbitmq1:15692']
        labels:
          node: rabbitmq1
          instance: rabbitmq1

  - job_name: 'rabbitmq-node2'
    static_configs:
      - targets: ['rabbitmq2:15692']
        labels:
          node: rabbitmq2
          instance: rabbitmq2

  - job_name: 'rabbitmq-node3'
    static_configs:
      - targets: ['rabbitmq3:15692']
        labels:
          node: rabbitmq3
          instance: rabbitmq3
